### ISSUE TITLE
fails to build with aeson-2.0

### ISSUE THREAD

**Issue by juhp** [haskell-works/avro#170]
```
avro                      > /tmp/stack-e0cde8ed4b1cb895/avro-0.5.2.1/src/Data/Avro/Schema/Schema.hs:526:21: error:
avro                      >     • Couldn't match expected type ‘A.Key’ with actual type ‘Text’
avro                      >     • In the second argument of ‘(.:?)’, namely ‘("order" :: Text)’
avro                      >       In the first argument of ‘(.!=)’, namely ‘o .:? ("order" :: Text)’
avro                      >       In a stmt of a 'do' block:
avro                      >         order <- o .:? ("order" :: Text) .!= Just Ascending
avro                      >     |
avro                      > 526 |     order <- o .:? ("order" :: Text)    .!= Just Ascending
avro                      >     |                     ^^^^^^^^^^^^^^^
avro                      > 
avro                      > /tmp/stack-e0cde8ed4b1cb895/avro-0.5.2.1/src/Data/Avro/Schema/Schema.hs:650:37: error:
avro                      >     • Couldn't match type: HashMap Text A.Value
avro                      >                      with: Data.Aeson.KeyMap.KeyMap A.Value
avro                      >       Expected: A.Object
avro                      >         Actual: HashMap Text A.Value
avro                      >     • In the first argument of ‘A.Object’, namely
avro                      >         ‘(HashMap.map toJSON mp)’
avro                      >       In the expression: A.Object (HashMap.map toJSON mp)
avro                      >       In a case alternative: DMap mp -> A.Object (HashMap.map toJSON mp)
avro                      >     |
avro                      > 650 |       DMap mp          -> A.Object (HashMap.map toJSON mp)
avro                      >     |                                     ^^^^^^^^^^^^^^^^^^^^^
avro                      > 
avro                      > /tmp/stack-e0cde8ed4b1cb895/avro-0.5.2.1/src/Data/Avro/Schema/Schema.hs:651:37: error:
avro                      >     • Couldn't match type: HashMap Text A.Value
avro                      >                      with: Data.Aeson.KeyMap.KeyMap A.Value
avro                      >       Expected: A.Object
avro                      >         Actual: HashMap Text A.Value
avro                      >     • In the first argument of ‘A.Object’, namely
avro                      >         ‘(HashMap.map toJSON flds)’
avro                      >       In the expression: A.Object (HashMap.map toJSON flds)
avro                      >       In a case alternative:
avro                      >           DRecord _ flds -> A.Object (HashMap.map toJSON flds)
avro                      >     |
avro                      > 651 |       DRecord _ flds   -> A.Object (HashMap.map toJSON flds)
avro                      >     |                                     ^^^^^^^^^^^^^^^^^^^^^^^
avro                      > 
avro                      > /tmp/stack-e0cde8ed4b1cb895/avro-0.5.2.1/src/Data/Avro/Schema/Schema.hs:653:36: error:
avro                      >     • Couldn't match expected type ‘A.Key’ with actual type ‘Text’
avro                      >     • In the first argument of ‘(.=)’, namely ‘typeName ty’
avro                      >       In the expression: typeName ty .= val
avro                      >       In the first argument of ‘object’, namely ‘[typeName ty .= val]’
avro                      >     |
avro                      > 653 |       DUnion _ ty val  -> object [ typeName ty .= val ]
avro                      >     |                                    ^^^^^^^^^^^
avro                      > 
avro                      > /tmp/stack-e0cde8ed4b1cb895/avro-0.5.2.1/src/Data/Avro/Schema/Schema.hs:777:35: error:
avro                      >     • Couldn't match type ‘Data.Aeson.KeyMap.KeyMap’
avro                      >                      with ‘HashMap Text’
avro                      >       Expected: Result (HashMap Text DefaultValue)
avro                      >         Actual: Result (Data.Aeson.KeyMap.KeyMap DefaultValue)
avro                      >     • In the second argument of ‘(<$>)’, namely
avro                      >         ‘mapM (parseAvroJSON union env mTy) obj’
avro                      >       In the expression: DMap <$> mapM (parseAvroJSON union env mTy) obj
avro                      >       In a case alternative:
avro                      >           Map mTy -> DMap <$> mapM (parseAvroJSON union env mTy) obj
avro                      >     |
avro                      > 777 |           Map mTy     -> DMap <$> mapM (parseAvroJSON union env mTy) obj
avro                      >     |                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
avro                      > 
avro                      > /tmp/stack-e0cde8ed4b1cb895/avro-0.5.2.1/src/Data/Avro/Schema/Schema.hs:780:53: error:
avro                      >     • Couldn't match type: Data.Aeson.KeyMap.KeyMap A.Value
avro                      >                      with: HashMap Text A.Value
avro                      >       Expected: HashMap Text A.Value
avro                      >         Actual: A.Object
avro                      >     • In the second argument of ‘HashMap.lookup’, namely ‘obj’
avro                      >       In the expression: HashMap.lookup (fldName f) obj
avro                      >       In the expression:
avro                      >         case HashMap.lookup (fldName f) obj of
avro                      >           Nothing
avro                      >             -> case fldDefault f of
avro                      >                  Just v -> return v
avro                      >                  Nothing
avro                      >                    -> fail
avro                      >                         $ "Decode failure: No record field '"
avro                      >                             <> T.unpack (fldName f) <> "' and no default in schema."
avro                      >           Just v -> parseAvroJSON union env (fldType f) v
avro                      >     |
avro                      > 780 |                     case HashMap.lookup (fldName f) obj of
avro                      >     |                                                     ^^^
```
