### PR TITLE
Remove comment in splice

### PR DESCRIPTION
**Pull request by alexbiehl**
Haddock doesn't like it and fails because it thinks it's section syntax:

```
src/Data/Avro/Deriving.hs:465:15: error:
    parse error on input ‘-- $(schemaDef' sch)’
    |
465 |       x = sch -- $(schemaDef' sch)
    |               ^^^^^^^^^^^^^^^^^^^^
```

### CODE REVIEW

**Comment by AlexeyRaga** [comment]
Hmm, out of interest, which version of `GHC`? 
It works fine with `8.4.4` and `8.6.5` in our projects, and in CI...

**Comment by alexbiehl** [comment]
Interesting, that specific project was using 8.4.4!
