### ISSUE TITLE
`deriveAvro` example doesn't work

### ISSUE THREAD

**Issue by Sir4ur0n** [haskell-works/avro#113]
Hi,

I just started testing this library and the `deriveAvro` example doesn't seem to work:
* `person.avsc`
```js
{
  "type": "record",
  "name": "Person",
  "fields": [
    {
      "name": "name",
      "type": "string"
    }
  ]
}
```
* `MyModule.hs`
```haskell
{-# LANGUAGE TemplateHaskell #-}
{-# LANGUAGE DeriveGeneric   #-}

module MyModule where

import Data.Avro.Deriving

deriveAvro "schemas/person.avsc"
```
* Stack resolver 13.26

I get this compilation error:
```
    • Couldn't match expected type ‘GHC.Exts.Item
                                      (f0 (Data.Text.Internal.Text,
                                           Data.Avro.Types.Value.Value Data.Avro.Schema.Type))’
                  with actual type ‘(Data.Text.Internal.Text,
                                     Data.Avro.Types.Value.Value Data.Avro.Schema.Type)’
      The type variable ‘f0’ is ambiguous
    • In the expression:
        (Data.Text.pack "name" Data.Avro.ToAvro..= p_1_alvH)
      In the second argument of ‘Data.Avro.record’, namely
        ‘[(Data.Text.pack "name" Data.Avro.ToAvro..= p_1_alvH)]’
      In the expression:
        (Data.Avro.record schema'Person)
          [(Data.Text.pack "name" Data.Avro.ToAvro..= p_1_alvH)]
  |
8 | deriveAvro "schemas/person.avsc"
  | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

```

However this compiles fine with `deriveFromAvro`

Is there something I missed? I may very well have done an error :sweat_smile: 

Cheers!

**Comment by Kheldar** [comment]
Works on my machine against LTS-13.26. Do you perhaps have something unusual about the way you've set up stack/cabal/ghc?

**Comment by Sir4ur0n** [comment]
I just tested on my Windows machine and this works. So I guess this is something NixOS related 🤔 I'll investigate on my side and explain in this issue when I find out. Sorry for bothering you 😞 Cheers!
