### ISSUE TITLE
Does not compile on `ghc-8.8.1`

### ISSUE THREAD

**Issue by newhoggy** [haskell-works/avro#121]
```
Building library for avro-0.4.5.2..
[ 1 of 28] Compiling Data.Avro.Codec  ( src/Data/Avro/Codec.hs, dist/build/Data/Avro/Codec.o )
[ 2 of 28] Compiling Data.Avro.Decode.Lazy.LazyValue ( src/Data/Avro/Decode/Lazy/LazyValue.hs, dist/build/Data/Avro/Decode/Lazy/LazyValue.o )
[ 3 of 28] Compiling Data.Avro.Decode.Strict ( src/Data/Avro/Decode/Strict.hs, dist/build/Data/Avro/Decode/Strict.o )
[ 4 of 28] Compiling Data.Avro.Types.Value ( src/Data/Avro/Types/Value.hs, dist/build/Data/Avro/Types/Value.o )
[ 5 of 28] Compiling Data.Avro.Types  ( src/Data/Avro/Types.hs, dist/build/Data/Avro/Types.o )
[ 6 of 28] Compiling Data.Avro.Schema ( src/Data/Avro/Schema.hs, dist/build/Data/Avro/Schema.o )

src/Data/Avro/Schema.hs:523:3: error:
    ‘fail’ is not a (visible) method of class ‘Monad’
    |
523 |   fail = MF.fail
    |   ^^^^
```
